// flow-typed signature: 73c369c5c906a0d82346a0c3f20b3047
// flow-typed version: <<STUB>>/preact-hook-htm_v^0.3.1-beta/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-hook-htm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-hook-htm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-hook-htm/dist/preact-hook-htm.cjs' {
  declare module.exports: any;
}

declare module 'preact-hook-htm/dist/preact-hook-htm.esm' {
  declare module.exports: any;
}

declare module 'preact-hook-htm/dist/preact-hook-htm.umd' {
  declare module.exports: any;
}

declare module 'preact-hook-htm/rollup.config' {
  declare module.exports: any;
}

declare module 'preact-hook-htm/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-hook-htm/dist/preact-hook-htm.cjs.js' {
  declare module.exports: $Exports<'preact-hook-htm/dist/preact-hook-htm.cjs'>;
}
declare module 'preact-hook-htm/dist/preact-hook-htm.esm.js' {
  declare module.exports: $Exports<'preact-hook-htm/dist/preact-hook-htm.esm'>;
}
declare module 'preact-hook-htm/dist/preact-hook-htm.umd.js' {
  declare module.exports: $Exports<'preact-hook-htm/dist/preact-hook-htm.umd'>;
}
declare module 'preact-hook-htm/rollup.config.js' {
  declare module.exports: $Exports<'preact-hook-htm/rollup.config'>;
}
declare module 'preact-hook-htm/src/index.js' {
  declare module.exports: $Exports<'preact-hook-htm/src/index'>;
}
